# 1.0 Instalando Bibliotecas

In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

# 2.0 Carregando os Dados

In [6]:
df_micro = pd.read_csv("../data/microdados_enem_2023.csv", sep=";", encoding="latin1")

## 2.1 Configurações

In [16]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

## 2.2 Conhecimento inicial da Base

In [17]:
df_micro.head()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TX_RESPOSTAS_CN,TX_RESPOSTAS_CH,TX_RESPOSTAS_LC,TX_RESPOSTAS_MT,TP_LINGUA,TX_GABARITO_CN,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,210059085136,2023,14,M,2,1,1,1,17,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A,F,E,D,5,F,C,C,D,C,D,C,B,B,D,C,C,B,B,A,B,B,A,A,B
1,210059527735,2023,12,M,2,1,0,1,16,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5300108,Brasília,53,DF,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,F,E,E,B,3,H,A,B,C,C,A,B,B,B,A,B,A,B,B,A,A,C,A,D,B
2,210061103945,2023,6,F,1,1,1,1,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4305108,Caxias do Sul,43,RS,1,1,1,1,1221.0,1193.0,1204.0,1211.0,502.0,498.9,475.6,363.2,DBEBDCECCBCEBBBBDBABDDBBAABCBACDBACECCBAADEBB,ABDEADAADCDABDCADAEABCDDCBAADCCBEBCEBEBDBEAED,ACEBDCABAACAEBAECEBBBAAECBBDEADCAECCCEDDABEED,CEAEACCCDABCDAACEDDBAAEBABDDEEBDAECABDBCBCADE,1,DBEABDABDCACDBECDDDBCAAABBACCCADEBECCCEDAEEED,ACEEABAADCDAADEABCDABCDCABCBDADEBAECABADBCDAE,DBABBAEBAAAACDACDEDAACADBADBCCEACCCEAAECBBEBCA...,BCCDEEABCBEDCEABBEBDABDDADDADECAADDCCBEBEABCC,1.0,140.0,200.0,100.0,120.0,140.0,700.0,H,E,C,F,5,C,A,B,D,B,A,B,A,B,A,B,A,A,B,A,A,A,A,A,B
3,210060214087,2023,2,F,1,3,1,2,0,2,1.0,0,2304400.0,Fortaleza,23.0,CE,2.0,1.0,1.0,2304400,Fortaleza,23,CE,1,1,1,1,1224.0,1192.0,1202.0,1214.0,459.0,508.5,507.2,466.7,DEEBEACCCEBDDBDCCCAEEDCBAAADBCBEEEDCDAAECBEEC,DDAAEEBCCDEADBCDDCBAECABEBDEBDABECECEDCDDAEED,ADBDADAEEEACAABBACADCAEBBAAEBBCDEBBDDADDCADAA,EECBAEDEEDDDBBAADEECDBBBECEAACEAEECDBEDDBCDCB,0,CDDDABBABDBEABDECCEEEDCEDAEBABDCCAACCCADACDBE,DBAADEADCDCABABCDDEBAEABAECABAACECDAECBDAABCD,BBBDAABAEACCEEEDEACBCACAACAACAAAECBBEDBCCADBDE...,EBDADDAEBEACBEDCECCBEABCADEBCCBCCDEBDDAABBADD,1.0,140.0,200.0,160.0,180.0,200.0,880.0,D,D,B,B,5,C,A,B,B,A,A,B,A,A,A,A,A,A,B,A,A,D,A,A,B
4,210059980948,2023,3,F,1,3,1,2,0,2,1.0,0,2311306.0,Quixadá,23.0,CE,2.0,1.0,1.0,2311306,Quixadá,23,CE,1,1,1,1,1222.0,1191.0,1201.0,1212.0,402.5,379.2,446.9,338.3,AECCEAACDEABEEECDBAEEAAADDEABCBCEBACEEDCBEABD,CADEBCEDDEBCBAEBADDCECACADBDEBABDBDBEEDBBEADC,AABBACBCAEDABDADEDAACCAEEEECAACDCADBAEACDEAAE,CDBABEDCEEBBBDECDEBACCAABDEDCBECDECABBDBDEECC,0,CAAADCCCCDDDABDCACDBEEEDCEDAEECCDBEABDBABBAEB,CDAEECABAACEAADECBDAABCDCABADCDEABAABCDDEBADB,BBDABAAEBADACEEDCCDBADBDEDCCEBCACEACAACAACACBB...,DCECACCBDECBEEABEABDDAADDABBBCCBCCDDAEBDADEEB,1.0,120.0,120.0,120.0,120.0,80.0,560.0,B,B,A,A,4,B,A,B,A,A,A,B,A,A,A,A,A,A,B,A,A,B,A,A,A

In [27]:
# Transform .shape em duas variáveis
n_linhas, n_colunas = df_micro.shape

# Formatando o print
print(f"Quantidade de linhas: {n_linhas}. Quantidade de colunas: {n_colunas}")

Quantidade de linhas: 3933955. Quantidade de colunas: 76

In [19]:
df_micro.dtypes

NU_INSCRICAO                int64
NU_ANO                      int64
TP_FAIXA_ETARIA             int64
TP_SEXO                    object
TP_ESTADO_CIVIL             int64
TP_COR_RACA                 int64
TP_NACIONALIDADE            int64
TP_ST_CONCLUSAO             int64
TP_ANO_CONCLUIU             int64
TP_ESCOLA                   int64
TP_ENSINO                 float64
IN_TREINEIRO                int64
CO_MUNICIPIO_ESC          float64
NO_MUNICIPIO_ESC           object
CO_UF_ESC                 float64
SG_UF_ESC                  object
TP_DEPENDENCIA_ADM_ESC    float64
TP_LOCALIZACAO_ESC        float64
TP_SIT_FUNC_ESC           float64
CO_MUNICIPIO_PROVA          int64
NO_MUNICIPIO_PROVA         object
CO_UF_PROVA                 int64
SG_UF_PROVA                object
TP_PRESENCA_CN              int64
TP_PRESENCA_CH              int64
TP_PRESENCA_LC              int64
TP_PRESENCA_MT              int64
CO_PROVA_CN               float64
CO_PROVA_CH               float64
CO_PROVA_LC               float64
CO_PROVA_MT               float64
NU_NOTA_CN                float64
NU_NOTA_CH                float64
NU_NOTA_LC                float64
NU_NOTA_MT                float64
TX_RESPOSTAS_CN            object
TX_RESPOSTAS_CH            object
TX_RESPOSTAS_LC            object
TX_RESPOSTAS_MT            object
TP_LINGUA                   int64
TX_GABARITO_CN             object
TX_GABARITO_CH             object
TX_GABARITO_LC             object
TX_GABARITO_MT             object
TP_STATUS_REDACAO         float64
NU_NOTA_COMP1             float64
NU_NOTA_COMP2             float64
NU_NOTA_COMP3             float64
NU_NOTA_COMP4             float64
NU_NOTA_COMP5             float64
NU_NOTA_REDACAO           float64
Q001                       object
Q002                       object
Q003                       object
Q004                       object
Q005                        int64
Q006                       object
Q007                       object
Q008                       object
Q009                       object
Q010                       object
Q011                       object
Q012                       object
Q013                       object
Q014                       object
Q015                       object
Q016                       object
Q017                       object
Q018                       object
Q019                       object
Q020                       object
Q021                       object
Q022                       object
Q023                       object
Q024                       object
Q025                       object
dtype: object

## 3.0 Limpeza dos Dados

In [25]:
# 1. Contagem absoluta de valores em branco por coluna
missing_counts = df_micro.isnull().sum()

# 2. Percentual de valores em branco por coluna
missing_perc = df_micro.isnull().mean() * 100

# 3. Combinar em um DataFrame organizado
missing_df = pd.concat(
    [missing_counts, missing_perc],
    axis=1,
    keys=['missing_count', 'missing_pct']
).sort_values(by='missing_count', ascending=False)

In [26]:
missing_df

                        missing_count  missing_pct
TP_LOCALIZACAO_ESC            2975449    75.635054
CO_UF_ESC                     2975449    75.635054
TP_SIT_FUNC_ESC               2975449    75.635054
TP_DEPENDENCIA_ADM_ESC        2975449    75.635054
SG_UF_ESC                     2975449    75.635054
CO_MUNICIPIO_ESC              2975449    75.635054
NO_MUNICIPIO_ESC              2975449    75.635054
TP_ENSINO                     2594874    65.960948
NU_NOTA_CN                    1241528    31.559283
CO_PROVA_MT                   1241528    31.559283
CO_PROVA_CN                   1241528    31.559283
TX_RESPOSTAS_CN               1241528    31.559283
TX_GABARITO_CN                1241528    31.559283
NU_NOTA_MT                    1241528    31.559283
TX_RESPOSTAS_MT               1241528    31.559283
TX_GABARITO_MT                1241528    31.559283
TP_STATUS_REDACAO             1111312    28.249230
NU_NOTA_CH                    1111312    28.249230
NU_NOTA_REDACAO               1111312    28.249230
CO_PROVA_LC                   1111312    28.249230
CO_PROVA_CH                   1111312    28.249230
NU_NOTA_COMP5                 1111312    28.249230
NU_NOTA_COMP4                 1111312    28.249230
TX_RESPOSTAS_CH               1111312    28.249230
TX_RESPOSTAS_LC               1111312    28.249230
NU_NOTA_COMP3                 1111312    28.249230
TX_GABARITO_CH                1111312    28.249230
TX_GABARITO_LC                1111312    28.249230
NU_NOTA_COMP2                 1111312    28.249230
NU_NOTA_COMP1                 1111312    28.249230
NU_NOTA_LC                    1111312    28.249230
Q007                                0     0.000000
Q006                                0     0.000000
Q005                                0     0.000000
Q008                                0     0.000000
Q003                                0     0.000000
Q009                                0     0.000000
Q024                                0     0.000000
Q023                                0     0.000000
Q022                                0     0.000000
Q021                                0     0.000000
Q020                                0     0.000000
Q019                                0     0.000000
Q018                                0     0.000000
Q017                                0     0.000000
Q016                                0     0.000000
Q015                                0     0.000000
Q014                                0     0.000000
Q013                                0     0.000000
Q012                                0     0.000000
Q011                                0     0.000000
Q010                                0     0.000000
Q004                                0     0.000000
NU_INSCRICAO                        0     0.000000
Q002                                0     0.000000
Q001                                0     0.000000
TP_FAIXA_ETARIA                     0     0.000000
TP_SEXO                             0     0.000000
TP_ESTADO_CIVIL                     0     0.000000
TP_COR_RACA                         0     0.000000
TP_NACIONALIDADE                    0     0.000000
TP_ST_CONCLUSAO                     0     0.000000
TP_ANO_CONCLUIU                     0     0.000000
TP_ESCOLA                           0     0.000000
IN_TREINEIRO                        0     0.000000
CO_MUNICIPIO_PROVA                  0     0.000000
NO_MUNICIPIO_PROVA                  0     0.000000
CO_UF_PROVA                         0     0.000000
SG_UF_PROVA                         0     0.000000
TP_PRESENCA_CN                      0     0.000000
TP_PRESENCA_CH                      0     0.000000
TP_PRESENCA_LC                      0     0.000000
TP_PRESENCA_MT                      0     0.000000
NU_ANO                              0     0.000000
TP_LINGUA                           0     0.000000
Q025                                0     0.000000

In [28]:
df_micro.describe()

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_ESC,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,CO_MUNICIPIO_PROVA,CO_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,CO_PROVA_CN,CO_PROVA_CH,CO_PROVA_LC,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO,Q005
count,3.933955e+06,3933955.0,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,1.339081e+06,3.933955e+06,9.585060e+05,958506.000000,958506.000000,958506.000000,958506.000000,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,3.933955e+06,2.692427e+06,2.822643e+06,2.822643e+06,2.692427e+06,2.692427e+06,2.822643e+06,2.822643e+06,2.692427e+06,3.933955e+06,2.822643e+06,2.822643e+06,2.822643e+06,2.822643e+06,2.822643e+06,2.822643e+06,2.822643e+06,3.933955e+06
mean,2.100601e+11,2023.0,5.096262e+00,1.043938e+00,2.058200e+00,1.028277e+00,1.684697e+00,2.445029e+00,1.415810e+00,1.005142e+00,1.576192e-01,3.191200e+06,31.764971,2.437952,1.037193,1.016525,3.081860e+06,3.067459e+01,6.855317e-01,7.198453e-01,7.198453e-01,6.855317e-01,1.222665e+03,1.192657e+03,1.202655e+03,1.212665e+03,4.957515e+02,5.233542e+02,5.181466e+02,5.338357e+02,4.570085e-01,1.152402e+00,1.215452e+02,1.392952e+02,1.185090e+02,1.297970e+02,1.086520e+02,6.177985e+02,3.688928e+00
std,1.154550e+06,0.0,3.871855e+00,4.120029e-01,1.003314e+00,2.127761e-01,7.467924e-01,4.450337e+00,6.018231e-01,7.152547e-02,3.643837e-01,1.020263e+06,10.176427,0.909037,0.189235,0.203970,9.993460e+05,9.964075e+00,4.655133e-01,4.516699e-01,4.516699e-01,4.655133e-01,3.691471e+00,3.591161e+00,3.590874e+00,3.691568e+00,8.792872e+01,8.857106e+01,7.545243e+01,1.316478e+02,4.981484e-01,8.001447e-01,3.565444e+01,5.161563e+01,4.340828e+01,4.377326e+01,6.160248e+01,2.146211e+02,1.409879e+00
min,2.100580e+11,2023.0,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.100015e+06,11.000000,1.000000,1.000000,1.000000,1.100015e+06,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.221000e+03,1.191000e+03,1.201000e+03,1.211000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
25%,2.100591e+11,2023.0,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,2.401008e+06,24.000000,2.000000,1.000000,1.000000,2.403251e+06,2.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.222000e+03,1.192000e+03,1.202000e+03,1.212000e+03,4.405000e+02,4.678000e+02,4.714000e+02,4.312000e+02,0.000000e+00,1.000000e+00,1.200000e+02,1.200000e+02,1.000000e+02,1.200000e+02,6.000000e+01,5.000000e+02,3.000000e+00
50%,2.100601e+11,2023.0,3.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,3.205002e+06,32.000000,2.000000,1.000000,1.000000,3.107307e+06,3.100000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.223000e+03,1.193000e+03,1.203000e+03,1.213000e+03,4.939000e+02,5.304000e+02,5.231000e+02,5.236000e+02,0.000000e+00,1.000000e+00,1.200000e+02,1.400000e+02,1.200000e+02,1.200000e+02,1.200000e+02,6.200000e+02,4.000000e+00
75%,2.100611e+11,2023.0,7.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,3.550308e+06,35.000000,2.000000,1.000000,1.000000,3.548906e+06,3.500000e+01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.224000e+03,1.194000e+03,1.204000e+03,1.214000e+03,5.512000e+02,5.849000e+02,5.703000e+02,6.301000e+02,1.000000e+00,1.000000e+00,1.400000e+02,1.800000e+02,1.400000e+02,1.600000e+02,1.600000e+02,7.800000e+02,4.000000e+00
max,2.100621e+11,2023.0,2.000000e+01,4.000000e+00,5.000000e+00,4.000000e+00,4.000000e+00,1.700000e+01,3.000000e+00,2.000000e+00,1.000000e+00,5.300108e+06,53.000000,4.000000,2.000000,4.000000,5.300108e+06,5.300000e+01,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.304000e+03,1.274000e+03,1.284000e+03,1.294000e+03,8.684000e+02,8.230000e+02,8.208000e+02,9.586000e+02,1.000000e+00,9.000000e+00,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02,2.000000e+02,1.000000e+03,2.000000e+01